name: Workflow
on:
  workflow_dispatch:
  schedule:
    # "At 17:01."
    #  https://crontab.guru/#1_17_*_*_*
    - cron: "1 17 * * *"

permissions:
  contents: write

jobs:
  fetch_publish:
    name: Fetch and publish
    runs-on: ubuntu-latest
    env:
      downloaded_html_file_name: "homepage.html"
      generated_markdown_file_name: "upcoming_live.md"
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 1

      - name: Data
        run: |
          set -e
          1>'${{ env.generated_markdown_file_name }}' \
            bash \
            ./the_script.sh \
              '432000' \
              '${{ env.downloaded_html_file_name }}'

      - name: Read ${{ env.generated_markdown_file_name }}
        id: read_result_file
        uses: juliangruber/read-file-action@v1.1.8
        with:
          path: ${{ env.generated_markdown_file_name }}

      - name: What time?
        id: my_luminous_watch
        uses: josStorer/get-current-time@v2.1.3
        with:
          format: "YYYYMMDDHHmmss"

      - name: Upload artifact "${{ env.downloaded_html_file_name }}"
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ steps.my_luminous_watch.outputs.formattedTime }}_${{ env.downloaded_html_file_name }}
          path: ${{ env.downloaded_html_file_name }}

      - name: Upload artifact "${{ env.generated_markdown_file_name }}"
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ steps.my_luminous_watch.outputs.formattedTime }}_${{ env.generated_markdown_file_name }}
          path: ${{ env.generated_markdown_file_name }}

      - name: Publish a release
        uses: ncipollo/release-action@v1.21.0
        with:
          name: "Upcoming live: ${{ steps.my_luminous_watch.outputs.readableTime }}"
          tag: ${{ steps.my_luminous_watch.outputs.formattedTime }}
          artifacts: "${{ env.generated_markdown_file_name }}"
          body: ${{ steps.read_result_file.outputs.content }}
